### ISSUE TITLE
Backend: votre go.mod n'inclut aucun client Prisma à utiliser

### ISSUE THREAD

**Issue by charafzellou** [Yassine94110/dex_pa#21]
Votre go.mod n'inclut aucun client Prisma à utiliser
Vous utilisez un driver `Postgres` que vous nommez Prisma, ce qui porte à confusion.
La méthode `prisma.Client.Disconnect()` ne semble pas exister dans ce contexte.!
Pareil pour le type `PrismaClient` dans vos structures.

**Comment by hmzaakun** [comment]
done on branch 13-15API
